#!/usr/bin/env sh
set -euo

option=$(fuzzel --dmenu --minimal-lines <<-EOF
	Lock
	Suspend
	Reboot
	Hibernate
	Power off
EOF
)

case ${option} in
	"Lock") loginctl lock-session ;;
	"Suspend") loginctl lock-session && systemctl suspend ;;
	"Reboot") reboot ;;
	"Hibernate") systemctl hibernate ;;
	"Power off") systemctl poweroff ;;
esac
